#!/usr/bin/python2.4
#
# Copyright 2009 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the 'License')
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Benchmark Tests Definitions."""

import logging

from categories import test_set_base


_CATEGORY = 'v8'


class V8Test(test_set_base.TestBase):
  TESTS_URL_PATH = '/%s/test' % _CATEGORY

  def __init__(self, key, name, doc):
    """Initialze a benchmark test.

    Args:
      key: key for this in dict's
      name: a human readable label for display
      url_name: the name used in the url
      score_type: 'boolean' or 'custom'
      doc: a description of the test
      value_range: (min_value, max_value) as integer values
      is_hidden_stat: whether or not the test shown in the stats table
    """
    test_set_base.TestBase.__init__(
        self,
        key=key,
        name=name,
        url=self.TESTS_URL_PATH,
        score_type='custom',
        doc=doc,
        min_value=0,
        max_value=60000)

  def GetScoreAndDisplayValue(self, median):
    """Returns a tuple with display text for the cell as well as a 1-100 value.
    """
    if median == None or median == '':
      return 0, ''

    median = int(median)
    score = median
    display = median
    return score, display


_TESTS = (
  # key, name, doc
  V8Test(
    'Richards', 'Richards', 'OS kernel simulation benchmark, originally written in BCPL by Martin Richards (<i>539 lines</i>).'
  ),
  V8Test(
    'DeltaBlue', 'DeltaBlue', 'One-way constraint solver, originally written in Smalltalk by John Maloney and Mario Wolczko (<i>880 lines</i>).'
  ),
  V8Test(
    'Crypto', 'Crypto', 'Encryption and decryption benchmark based on code by Tom Wu (<i>1698 lines</i>).'
  ),
  V8Test(
    'RayTrace', 'RayTrace', 'Ray tracer benchmark based on code by <a href="http://flog.co.nz/">Adam Burmister</a> (<i>935 lines</i>).'
  ),
  V8Test(
    'EarleyBoyer', 'EarleyBoyer', 'Classic Scheme benchmarks, translated to JavaScript by Florian Loitsch\'s Scheme2Js compiler (<i>4685 lines</i>).'
  ),
  V8Test(
    'RegExp', 'RegExp', 'Regular expression benchmark generated by extracting regular expression operations from 50 of the most popular web pages (<i>1614 lines</i>).'
  ),
  V8Test(
    'Splay', 'Splay', 'Data manipulation benchmark that deals with splay trees and exercises the automatic memory management subsystem (<i>378 lines</i>).'
  ),
  V8Test(
    'Overall', 'Overall Score', 'The overall score for all V8 Benchmark tests'
  ),
)

TEST_SET = test_set_base.TestSet(
    category=_CATEGORY,
    category_name='V8 Benchmark',
    subnav={
      'Test': '/%s/test' % _CATEGORY,
      'About': '/%s/about' % _CATEGORY,
    },
    home_intro = '''This is the V8 benchmark suite: A collection of pure JavaScript
benchmarks that the V8 team has used to tune V8.
V8 benchmarks reflect pure JavaScript performance while web applications running in a
web browser have tasks other than JavaScript to contend with, such as: waiting for a
network connection, manipulating the Document Object Model and rendering pages.
<a href="/v8/about">Read more about the V8 benchmark suite tests.</a>''',
    tests=_TESTS
)
